### ISSUE TITLE
اشتباه نوشتاری در بند اول

### ISSUE THREAD

**Issue by eshagh79** [rzashakeri/awesome-persian#1]
سلام، در بند اول "که" و "در" رو جابه‌جا نوشتید،
به تازگی جادی تو کانال تلگرامش یک کتاب درباره الگوریتم‌ها معرفی کرده، اگه میشه اونم به این لیست اضافه کنید.
https://t.me/jadivarlog/24

**Comment by rzashakeri** [comment]
> سلام، در بند اول "که" و "در" رو جابه‌جا نوشتید، به تازگی جادی تو کانال تلگرامش یک کتاب درباره الگوریتم‌ها معرفی کرده، اگه میشه اونم به این لیست اضافه کنید. https://t.me/jadivarlog/24


مرسی که گفتی برطرفش کردم 

اونم اضافه شده می‌تونید از طریق بخش [الگوریتم](https://github.com/rzashakeri/awesome-persian#%D8%A7%D9%84%DA%AF%D9%88%D8%B1%DB%8C%D8%AA%D9%85) بهش دسترسی داشته باشید
