### ISSUE TITLE
بهبود توضیحات مخزن

### ISSUE THREAD

**Issue by farooqkz** [rzashakeri/awesome-persian#3]
پیشنهاد بنده:

هر چیز عالی‌ای که در دنیای فارسی‌زبان‌ها وجود داره مثل کتاب‌ها، کتاب‌خونه‌ها، چهارچوب‌ها، دوره‌ها، سایت‌ها و هر چیز مرتبط دیگه‌ای. تمام منابع آموزشی معرفی‌شده رایگان هستن برای این‌که هیچ‌کس به خاطر نداشتن پول از آموزش عقب نمونه

در فارسی اصل بر جدا نویسی هست. همینوطور «فریم‌ورک» انگلیسی هست. فارسی‌اش «چهارچوب» هست.

پ‌ن: چرا یک قسمت برای «سایت‌ها» وجود نداره توی سند؟

**Comment by rzashakeri** [comment]
> پیشنهاد بنده:
> 
> هر چیز عالی‌ای که در دنیای فارسی‌زبان‌ها وجود داره مثل کتاب‌ها، کتاب‌خونه‌ها، چهارچوب‌ها، دوره‌ها، سایت‌ها و هر چیز مرتبط دیگه‌ای. تمام منابع آموزشی معرفی‌شده رایگان هستن برای این‌که هیچ‌کس به خاطر نداشتن پول از آموزش عقب نمونه
> 
> در فارسی اصل بر جدا نویسی هست. همینوطور «فریم‌ورک» انگلیسی هست. فارسی‌اش «چهارچوب» هست.
> 
> پ‌ن: چرا یک قسمت برای «سایت‌ها» وجود نداره توی سند؟


سلام 
مرسی بابت پیشنهادتو، اصلاح میشه 
و به مرور بخش های مختلف اضافه میشه
